#!/bin/sh

cd $BUILDDIR
cp -u $COMMONDIR/*.* $SRCDIR/run .

for file in `find -type f -name "*.*" -not -name "*.gz" -not -name "*.xz" -not -name "*.bzip2"`
do
  if [[ $file -nt $file.gz ]]; then gzip --stdout $file > $file.gz; fi
  if [[ $file -nt $file.xz ]]; then xz --stdout -9 $file > $file.xz; fi
  if [[ $file -nt $file.bzip2 ]]; then bzip2 --stdout -9 $file > $file.bzip2; fi
done
