#!/usr/bin/env ruby

puts "environment: - - - gzip-version #{`gzip --version | head -1`}"
puts "environment: - - - xz-version #{`xz --version | head -1`}"
puts "environment: - - - bzip2-version #{`bzip2 --help 2>&1 | head -1 | grep -oP "Version.*"`}"

Dir["*"].each do |file|
  id = file.scan(/^[^.]*/).first
  next if not file.start_with?(id + '.' + id)
  size = `du --bytes #{file} | grep -oP "^[0-9]+"`
  suffix = file.scan(/[^.]*$/).first
  suffix = "raw" if suffix == "bin" || suffix == id
  next if not %w(raw gz xz bzip2).include?(suffix)
  implementation = id.scan(/[^_]*$/).first || '-'
  id = id.scan(/^[^_]*/).first
  implementation = '-' if implementation == id
  puts "value: #{id} #{suffix} #{implementation} size #{size}"
end
